package: ./package.json
reporter: spec
timeout: 5000
ui: bdd
color: true
diff: true
inline-diffs: true
extension:
  - js
spec: test/**/*.test.js
file:
  - test/setup.test.js
  - test/usermodel.test.js
  - test/pollmodel.test.js
